export const TAG_SHORT = {
  prog1: 'Prog 1',
  prog2: 'Prog 2',
  formal: 'Formal',
  systems: 'Systems',
  adv: 'Adv CS',
  world: 'C & W',
  ai: 'AI',
  math: 'Math',
};

export const TAG_FULL = {
  prog1: 'Programming 1',
  prog2: 'Programming 2',
  formal: 'Formal Reasoning',
  systems: 'Systems',
  adv: 'Advanced CS',
  world: 'Computation & World',
  ai: 'Artificial Intelligence',
  math: 'Math prep',
};

export const TAG_CLASS = {
  prog1: 'prog',
  prog2: 'prog',
  formal: 'formal',
  systems: 'systems',
  adv: 'adv',
  world: 'world',
  ai: 'ai',
  math: 'math',
};

// Automatic tag lookup by course code (used in onboarding + history add)
export const TAG_AUTO = {
  'CS 50': ['prog1'],
  'CS 51': ['prog2'],
  'CS 32': ['prog1'],
  'CS 20': ['formal'],
  'CS 120': ['formal', 'complim'],
  'CS 1200': ['formal', 'complim'],
  'CS 121': ['formal', 'complim'],
  'CS 124': ['formal', 'alg', 'adv'],
  'CS 1240': ['formal', 'intalg', 'adv'],
  'CS 61': ['systems', 'adv'],
  'CS 161': ['systems', 'adv'],
  'CS 165': ['systems', 'adv'],
  'CS 181': ['world', 'ai', 'adv'],
  'CS 182': ['ai', 'adv'],
  'CS 1260': ['world', 'adv'],
  'CS 1340': ['world', 'adv'],
  'CS 1780': ['adv'],
  'CS 2780': ['adv'],
  'CS 91r': ['adv'],
  'CS 189': ['adv'],
  'CS 191': ['adv'],
  'CS 2241': ['adv'],
  'STAT 110': ['math'],
  'MATH 21b': ['math'],
  'MATH 21a': [],
  'MATH 22a': ['math'],
  'MATH 22b': ['math'],
  'MATH 25a': ['math'],
  'STAT 111': ['math'],
};

// Short title lookup for onboarding autocomplete
export const COURSE_TITLE = {
  'CS 50': 'Introduction to Computer Science',
  'CS 51': 'Abstraction and Design in Computation',
  'CS 32': 'Computational Thinking and Problem Solving',
  'CS 20': 'Discrete Mathematics for Computer Science',
  'CS 120': 'Introduction to Algorithms and their Limitations',
  'CS 1200': 'Theory of Computation',
  'CS 121': 'Introduction to Theoretical Computer Science',
  'CS 124': 'Data Structures and Algorithms',
  'CS 1240': 'Advanced Algorithms',
  'CS 61': 'Systems Programming and Machine Organization',
  'CS 161': 'Operating Systems',
  'CS 165': 'Data Systems',
  'CS 181': 'Machine Learning',
  'CS 182': 'Deep Learning',
  'CS 1260': 'Fairness and Privacy in Automated Decision Making',
  'CS 1340': 'Computing and the Law',
  'CS 1780': 'Usable Interactive Systems',
  'CS 2780': 'Usable Interactive Systems (Graduate)',
  'CS 91r': 'Supervised Research',
  'CS 189': 'Mathematics for Computation',
  'CS 191': 'Quantum Computing',
  'CS 2241': 'Information Theory',
  'STAT 110': 'Introduction to Probability',
  'MATH 21b': 'Linear Algebra and Differential Equations',
  'MATH 21a': 'Multivariable Calculus',
  'MATH 22a': 'Vector Calculus and Linear Algebra I',
  'MATH 22b': 'Vector Calculus and Linear Algebra II',
  'MATH 25a': 'Theoretical Linear Algebra and Real Analysis I',
  'STAT 111': 'Introduction to Statistical Inference',
};
